### ISSUE TITLE
Decoding different yaml types for a single node is tricky

### ISSUE THREAD

**Issue by AlistairB** [haskell-hvr/HsYAML#43]
In some cases you might have yaml like:

```yaml
list-o-things:
  - "Im text"
  - 2
  - name: complex-case
    extra-info: stuff
```

In `yaml` / `aeson` that is pretty simple to handle:

```haskell
newtype Thing = Thing Text

instance FromJSON Thing where
  parseJSON (String a) = pure $ Thing a
  parseJSON (Object v) =   -- v is a HashMap and quite easy to work with
```

In `HsYAML` there doesn't seem to ways to do this without getting deep into library internals.

```haskell
instance FromYAML Thing where
  parseYAML (Scalar _ (SStr a)) = pure $ Thing a
  parseYAML (Mapping _ _ _) = -- withMap would be redundant, but how else to write the parser?
```
