### ISSUE TITLE
Empty lines fail to round trip

### ISSUE THREAD

**Issue by TristanCacqueray** [haskell-hvr/HsYAML#48]
It seems like empty lines do not have a corresponding Event:

```yaml
a: 1

# comment
b: 2
```

Results in (after passing through `yaml-test yaml2yaml`):

```yaml
a: 1
# comment
b : 2
```

Would it be possible to add a new event or comment attribute to preserve empty lines?
