### ISSUE TITLE
Maping fields order is not preserved

### ISSUE THREAD

**Issue by majkrzak** [haskell-hvr/HsYAML#64]
Encoding the following mapping

```haskell
encode [mapping ["a" .= (1 :: Int), "d" .= (2 :: Int), "c" .= (3 :: Int), "b" .= (4 :: Int)]]
```
results in:
```yaml
a: 1
b: 4
c: 3
d: 2
```
